### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by ruchikxxii**
## UI improvements:
Added hover animation to the save button
## Added UI Changed depending on Campus:
the background image and the campus logo are set depending on the campus variable set in index.js
Currently the variable is hardcoded but can be set in future by passing an event from the backend
Final Looks:

auto-campnet-bits-pilani
auto-campnet-bits-goa
auto-campnet-bits-hyderabad

### CODE REVIEW

**Comment by riskycase** [comment]
@arihantbansal we can get some inputs from members of the respective campuses for these

**Comment by arihantbansal** [comment]
We can improve upon the BITS logo quality. The pixels are visible.

**Comment by arihantbansal** [comment]
And we can also look into changing around the blur, the black border on the blur card and more.

Basically, could revamp the entire design.

**Comment by riskycase** [comment]
Closing in favour of #24

**Pull request closed without merging**
